module.exports = combineReducers({
    banners: require('./api/banners.jsx'),
    catalog: require('./api/catalog.jsx'),
    openMenu: require('./api/openMenu.jsx'),
    city: require('./api/city.jsx'),
    shops: require('./api/shops.jsx'),
    iam: require('./api/iam.jsx'),
    shadow: require('./api/shadow.jsx'),
    actions: require('./api/actions.jsx'),
    products: require('./api/products.jsx'),
    product: require('./api/product.jsx'),
    cart: require('./api/cart.jsx'),
    login: require('./api/login.jsx'),
    company: require('./api/company.jsx'),
    meta: require('./api/meta.jsx'),
    vacancy: require('./api/vacancy.jsx'),
    journal: require('./api/journal.jsx'),
    journalCategory: require('./api/journalCategory.jsx'),
    journalArticle: require('./api/journalArticle.jsx'),
    popup: require('./api/popup.jsx')
});